### ISSUE TITLE
new st.css file breaks webpack and requires re-run

### ISSUE THREAD

**Issue by DeDuckProject** [wix/stylable-integration#15]
doing this:
```css
:import{
    -st-from: "./dimens.st.css";
    -st-named: radius,margin;
}
```
but without dimens.st.css existing yet.
I get this
`ERROR in Error: ENOENT: no such file or directory, stat '/Users/yiftachy/projects/core-3/wixplosives/auto-views/src/theme/dimens.st.css' "/Users/yiftachy/projects/core-3/wixplosives/auto-views/src/theme/dimens.st.css"
webpack: Failed to compile.
`

creating the correct file still doesn't result in reload, and I need to do `yarn start` for it to work
