### ISSUE TITLE
vars .st.css named import changes take affect only after restarting node

### ISSUE THREAD

**Issue by DeDuckProject** [wix/stylable-integration#16]
I have a dir with:
`theme.st.css`, `colors.st.css`

`colors.st.css`:
```css
:vars{
    primaryColor: #0074D9;
}
```

and `theme.st.css` uses it like so:
```css
:import{
    -st-from: "./colors.st.css";
    -st-named: primaryColor;
}
```
and later using `value(primaryColor)`. changes to color.st.css only take affect after running `yarn start`.
